server:
  port: ${PORT:8080}

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
      - id: authuser-service
        uri: https://localhost:8087/
        predicates:
        - Path=/ead-authuser/**
        
      - id: course-service
        uri: https://localhost:8082/
        predicates:
        - Path=/ead-course/**