server:
  port: ${PORT:8089}

spring:
  application:
    name: ead-notification-service
  datasource:
    url: jdbc:postgresql://localhost:5436/ead-notification
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true

logging:
  level:
    '[br.com.ead.notification]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost