server:
  port: ${PORT:8087}

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-authuser
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
        
logging:
  level:
    '[br.com.ead.authuser]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
ead:
  api:
    url:
      course: http://ead-course-service
