server:
  port: ${PORT:8087}

spring:
  application:
    name: Authuser-api
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-authuser
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true

    properties:
      hibernate:
        show_sql: true
        
logging:
  level:
    '[br.com.ead.authuser]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
