server:
  port: ${PORT:8088}

spring:
  application:
    name: Course-api
  datasource:
    url: jdbc:postgresql://localhost:5434/authuser-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true

    properties:
      hibernate:
        show_sql: true

