server:
  port: ${PORT:8082}

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5435/ead-course
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true

logging:
  level:
    '[br.com.ead.course]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
ead:
  api:
    url:
      authuser: http://ead-authuser-service